version: 0.2
phases:

  install:
    commands:
      - pip install cfn-lint
      - pip install awscli
  build:
    commands:
      - cfn-lint --template ./huit-public-resources-master-account.yml --regions $AWS_REGION
      - aws cloudformation validate-template --template-body file://$(pwd)/huit-public-resources-master-account.yml
      - cfn-lint --template ./huit-public-resources-child-account.yml --regions $AWS_REGION
      - aws cloudformation validate-template --template-body file://$(pwd)/huit-public-resources-child-account.yml
