version: 0.2

phases:
  install:
    commands:
      - pip install boto3
  build:
    commands:
      - echo "Validating resources..."
      - python buildautomation/huit-public-instance-smoketests.py
